### ISSUE TITLE
Password Policy Enumeration Results Printout Error

### ISSUE THREAD

**Issue by AzraelSec** [Wh1t3Fox/polenum#5]
The variable assignments on lines 51 and 52 should be moved to the outside if statement.
The correct piece of code should be like this:

```
if not lockout:
        if (low != 0):
            high = abs(high+1)
        else:
            high = abs(high)
            low = abs(low)

        tmp = low + (high)*16**8  # convert to 64bit int
        tmp *= (1e-7)  # convert to seconds
    else:
tmp = abs(high) * (1e-7)
```

Otherwise the _tmp_ variable would not be initialized and the rest of the code would not correctly interpret the data.

**Comment by Wh1t3Fox** [comment]
Good catch :+1:
