### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by sbrun** [Wh1t3Fox/polenum#6]
Hello
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).
Impacket is now Python 3 compatible. You should consider to switch polenum to Python 3. 

Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=937307

**Comment by Wh1t3Fox** [comment]
Fixed in #7
